aconv-chans: 32
aconv-filts: 15
adim: 128
atype: location
batch-size: 32
batch-sort-key: shuffle
bce-pos-weight: 1.0
cumulate-att-w: true
dlayers: 2
dropout-rate: 0.5
dunits: 1024
econv-chans: 512
econv-filts: 5
econv-layers: 3
elayers: 1
embed-dim: 512
epochs: 200
eps: 1e-6
eunits: 512
guided-attn-loss-sigma: 0.4
lr: 1e-3
maxlen-in: 150
maxlen-out: 400
patience: 0
postnet-chans: 512
postnet-filts: 5
postnet-layers: 5
prenet-layers: 2
prenet-units: 256
pretrained-model: model/phn/model.last1.avg.best
reduction-factor: 1
use-batch-norm: true
use-concate: true
use-guided-attn-loss: true
use-masking: true
use-residual: false
weight-decay: 0.0
zoneout-rate: 0.1
